services:
  # Frontend service
  - type: web
    name: fitgearhub-frontend
    env: node
    buildCommand: cd frontend && npm install && npm run build
    startCommand: cd frontend && npm start
    envVars:
      - key: NODE_ENV
        value: production

  # Backend service
  - type: web
    name: fitgearhub-backend
    env: python
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python manage.py migrate && python manage.py runserver 0.0.0.0:$PORT
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: project_name.settings
      - key: DEBUG
        value: "0"
      - key: DATABASE_URL
        fromDatabase:
          name: fitgearhub-db
          property: connectionString

databases:
  - name: fitgearhub-db
    databaseName: fitgearhub
    user: postgres 